language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-vagrant' ]; then cd .. && eval "mv $currentfolder generator-vagrant" && cd generator-vagrant; fi

